### ISSUE TITLE
Parsnp Error

### ISSUE THREAD

**Issue by alantsangmb** [marbl/harvest#11]
Hi

I am using parsnp to do genome alignment with different bacterial species without problem on a linux cluster platform. However, when I did parsnp on hundreds of E.coli complete genomes, following error occurred:

**ERROR**
The following command failed:
>>/tmp/_MEIUxjmZE/parsnp Ecoli_SNP_out/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

Is it due to the limited space on the /tmp directory on my cluster?
How can I solve this problem? Can I redirect the tmp files to another directory?
Thanks.

**Comment by alantsangmb** [comment]
Hi, I found that Error happen in another 91 genomes of Chlamydia trachomatis:

./parsnp -c -r ! -d Ctrachomatis_genomes -p 8 -o Ctrachomatis_out

|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
*************************************
SETTINGS:
|-refgenome:    autopick
|-aligner:      libMUSCLE
|-seqdir:       Ctrachomatis_SNP
|-outdir:       Ctrachomatis_SNP_out
|-OS:           Linux
|-threads:      8
*************************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from Ctrachomatis_SNP..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
  |->[OK]
-->Running PhiPack on LCBs to detect recombination..
  |->[SKIP]
-->Reconstructing core genome phylogeny..
**ERROR**
The following command failed:
>>/tmp/_MEIiyXf8c/ft -nt -quote -gamma -slow -boot 100 Ctrachomatis_SNP_out/parsnp.snps.mblocks > Ctrachomatis_SNP_out/parsnp.tree
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

**Comment by alantsangmb** [comment]
Sorry, problem solved.
I think it's my system problem.

**Comment by treangen** [comment]
>Sorry, problem solved.

ok, let me know if the issue resurfaces.

**Comment by joseiky** [comment]
Hello, I am trying to use Parsnp to align and obtain the phylogeny of 700+ isolates of K. pneumoniae. I already used it successfully to align 300+ E. coli genomes. However, I am unable to use it for the 700+ isolates. I keep on getting this error message:
/tmp/_MEIUxjmZE/parsnp Ecoli_SNP_out/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.

Can anyone be of help to me please?

**Comment by Shaokang123** [comment]
Same problem.

**Comment by hsmithfed** [comment]
I'm having the same problem as well, getting this message:
**ERROR**
The following command failed:
>>/tmp/_MEIDSBhx8/parsnp /home/ubuntu/Documents/Harvest/P_2019_10_21_102931369283/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**

I would love to know what might be causing this and how I could resolve it for future use!

**Comment by hao467** [comment]
-->Reading Genome (asm, fasta) files from /media/xwg/HJ/rename/fna/import/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
**ERROR**
The following command failed:
>>/tmp/_MEI8TX9MJ/parsnp tree3/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**
I am trying to run parsnp, the error message is pasted below.
Your help would be greatly appreciated!

**Comment by zhichusun** [comment]
SETTINGS:
|-refgenome:    autopick
|-aligner:      libMUSCLE
|-seqdir:       /xulie/human115cc
|-outdir:       /jieguo
|-OS:           Linux
|-threads:      32
************************

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from /xulie/human115cc..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
**ERROR**
The following command failed:
>>/tmp/_MEIeK6sMb/parsnp /jieguo/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR*
When I run the software, it can only analyze 95 genomes. The above problem will occur after 95 genomes.Can anyone be of help to me please?
