### ISSUE TITLE
How to use parsnp to align against a multi-chromosome reference?

### ISSUE THREAD

**Issue by minisciencegirl** [marbl/harvest#13]
Hi! I am trying to align my draft assemblies against the reference genome of the same species with parsnp to see how divergent these bacterial isolates are. My reference has three chromosomes, plus a number of plasmids. Should I concatenate the .fna files when I specify my reference (this won't work very well for the .gbk files)? Or would it be better to align the draft genomes against each of the chromosome separately?

Thanks!

**Comment by aphillippy** [comment]
Hello,
For a multi-chromosome reference you can pass a comma-separated list of GenBank files (one for each replicon). I think this is preferable to aligning each separately.

Best,
-Adam

**Comment by minisciencegirl** [comment]
Thanks Adam! 

Harvest is awesome by the way.

**Comment by aphillippy** [comment]
Happy you find it useful!
