### ISSUE TITLE
Missing VCF file

### ISSUE THREAD

**Issue by snayfach** [marbl/harvest#24]
Hi Todd,

I ran parsnp with the following command: 
`parsnp -r genome_dir/ref_genome.fna -d genome_dir/ -p 10`

And got the following output files: 
`parsnpAligner.ini  parsnpAligner.log  parsnp.ggr  parsnp.tree  parsnp.xmfa`

How can I get parsnp to produce a VCF file?

Thanks,
Stephen

**Comment by gotero** [comment]
You have to use harvesttools for that:

harvesttools -i parsnp.ggr -V parsnp.vcf

**Comment by snayfach** [comment]
Got it, thanks! That wasn't clear from the parsnp tutorial.
