### ISSUE TITLE
parsnp with genbank file error

### ISSUE THREAD

**Issue by sdewell** [marbl/harvest#25]
I've downloaded a genbank file (full) with sequence. when running parsnp as follows:

parsnp -g ../HE681097.1.gb -d .. -p 4 

i receive the following error:

-->Reading Genome (asm, fasta) files from ....
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ../HE681097.1.gb..
  |->[OK]
Traceback (most recent call last):
  File "<string>", line 624, in <module>
NameError: name 'nameok' is not defined

any help appreciated - thanks!

**Comment by idolawoye** [comment]
Hello, I'm having the same issues as above. Were you able to fix it? Thanks
